package problems_1_10;

public class Problem2
{
  /*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.

  Answer = 4613732
  */

  public static int eulerProblem2()
  {
    final int LIMIT = 4_000_000;
    int sum = 2, cur = 1, next = 2, temp;
    boolean isExceed = false;
    while (!isExceed)
    {
      temp = cur;
      cur = next;
      next += temp;
      isExceed = next > LIMIT;
      if ((next & 0x1) == 0 && !isExceed)
      {
        sum += next;
      }
    }
    return sum;
  }

}
