package problems_41_50;

public class Problem45
{
  /*
  Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

  Triangle	 	Tn = n(n+1)/2	 	1, 3, 6, 10, 15, ...
  Pentagonal	 	Pn = n(3n−1)/2	 	1, 5, 12, 22, 35, ...
  Hexagonal	 	Hn = n(2n−1)	 	1, 6, 15, 28, 45, ...
  It can be verified that T285 = P165 = H143 = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.

  Answer = 1533776805
   */


  private static long triangleNumber(long n)
  {
    return n * (n + 1) / 2;
  }

  private static double inversePentagonalNumber(long x)
  {
    return (Math.sqrt(24 * x + 1) + 1) / 6;
  }

  private static double inverseHexagonalNumber(long x)
  {
    return (Math.sqrt(8 * x + 1) + 1) / 4;
  }

  private static boolean isDoubleEquals(double f, double s)
  {
    return Math.abs(f - s) < 0.000001;
  }

  private static boolean isWholeNumber(double number)
  {
    return isDoubleEquals(number, Math.floor(number));
  }

  public static long eulerProblem45()
  {
    for (long t = 286; ; t++)
    {
      long i = triangleNumber(t);
      double p = inversePentagonalNumber(i);
      if (isWholeNumber(p))
      {
        double h = inverseHexagonalNumber(i);
        if (isWholeNumber(h))
          return i;
      }
    }
  }
}
